language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

services:
  - postgresql

env:
  - TOXENV=py-full DATABASE_URL=postgres://localhost/travis_ci_test

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py-base
    - python: "3.6"
      env: TOXENV=py-base
    - dist: xenial
      python: "3.7"
      env: TOXENV=py-full DATABASE_URL=postgres://localhost/travis_ci_test
    - python: "pypy"
      env: TOXENV=py-full
    - python: "pypy3"
      env: TOXENV=py-full

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install -U pip
install:
  - pip install -U codecov tox

before_script:
  - psql -c 'CREATE DATABASE travis_ci_test' -U postgres
script:
  - python setup.py test

after_success:
  - codecov

branches:
  only:
    - master
